### ISSUE TITLE
Support for raw images?

### ISSUE THREAD

**Issue by kwerle** [snap-diff/snap_diff-capybara#126]
I am interested in using this gem, but we also have some unit tests that return raw images.  Is it possible/easy to incorporate this gem into tests like:

```
  image_fixture_path = file_fixture("expected_images/image_for_this_test.png")
  actual_image = some.internal_api_call
  expect_actual_image_to_match(actual_image, image_fixture_path)
```

**Comment by pftg** [comment]
Yes, I’ll share later how I did it

Thanks,
Paul
