### ISSUE TITLE
Is it possible for capybara-screenshot-diff NOT to try to require minitest?

### ISSUE THREAD

**Issue by dolzenko** [snap-diff/snap_diff-capybara#85]
My problem is that I'm not using minitest in my Rails project, but it's being pulled in as a dependency by ActiveSupport and so this [1] test returns true and capybara-screenshot-diff thinks its in MiniTest context, which it isn't. I mean isn't it better to just check const_defined?(MiniTest) or something similar here: https://github.com/donv/capybara-screenshot-diff/blob/6a113e26f5e1fb664f0c359511744e00c9e3e89b/lib/capybara/screenshot/diff/drivers/utils.rb#L40C1-L46

[1] https://github.com/donv/capybara-screenshot-diff/blob/master/lib/capybara/screenshot/diff.rb#L104

**Comment by pftg** [comment]
Yeah we can do like capybara, use different files to require per different test frameworks

**Comment by pftg** [comment]
@dolzenko removed minitest for rspec integration
